name: Smoke Tests

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL to test against'
        required: false
        default: 'https://apaddcito-4.vercel.app'
        type: string
  push:
    branches:
      - main

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run smoke tests
        env:
          BASE_URL: ${{ github.event.inputs.base_url || 'https://apaddcito-4.vercel.app' }}
        run: npm run smoke:test